install.packages("ggplot2")
library(ggplot2)
install.packages("MASS")
library(MASS)
data <- read.csv("EMPLOYEE SATISFACTION SURVEY.csv")
head(data)
ggplot(data, aes(x=satlevel)) + 
  geom_histogram(binwidth=1, fill="blue", color="black", alpha=0.7) + 
  ggtitle("Histogram of Satisfaction Levels") + 
  theme_minimal()
qqnorm(data$satlevel)
qqline(data$satlevel, col = "red")
shapiro.test(data$satlevel)
median_satisfaction <- tapply(data$satlevel, data$dept, median)
print(median_satisfaction)
anova_result <- aov(satlevel ~ dept, data = data)
summary(anova_result)
data$Experience_Level <- ifelse(data$exp > 2, "Midlevel", "Junior")
head(data)
table_exp_satisfaction <- table(data$Experience_Level, data$satlevel)
chisq_test <- chisq.test(table_exp_satisfaction)
print(chisq_test)
count_satisfaction_gt3 <- aggregate(satlevel > 3 ~ dept, data = data, FUN = sum)
print(count_satisfaction_gt3)